models/clientedb.py
from peewee import Model, CharField, DateTimeField, Proxy
import datetime

db_proxy = Proxy()

class Cliente(Model):
    nome = CharField()
    email = CharField()
    idade = CharField()
    cidade= CharField()
    data_registro=DateTimeField(default=datetime.datetime.now)

    class Meta:
        database = db_proxy

main.py
from flask import Flask
from configuration import configurar_tudo

app= Flask(__name__)


configurar_tudo(app)

app.run(debug= True)

routes/clientes.py
from flask import Flask, Blueprint, render_template, url_for, request
from models.clientedb import Cliente
home_clientes = Blueprint('clientes', __name__)
#passo a passo:

# def de formulario de login = GET
@home_clientes.route('/novo')
def form_clientes():
    return render_template('form_clientes.html')

#editar cliente/editar=GET

@home_clientes.route('/<int:cliente_id>/editar')
def editar_clientes(cliente_id):
    cliente=Cliente.get(Cliente.id == cliente_id)

    return render_template('form_clientes.html', cliente=cliente)
    

# criar def de listar clientes = GET
@home_clientes.route('/')
def listar_clientes():
    clientes=Cliente.select()
    return render_template("listar_clientes.html", clientes=clientes)

# criar def de adicionar cliente/aicionar, inserir clientes novos no banco de dados = POST
@home_clientes.route('/', methods=['POST'])
def adicionar_clientes():
    data=request.json
    
    novo_usuario =Cliente.create(
        nome=data['nome'],
        idade=data['idade'],
        email=data['email'],
        cidade=data['cidade']
    )
    return render_template('item.html', cliente=novo_usuario)



#criar def de atualizar cliente/atualizar= PUT
@home_clientes.route('/<int:cliente_id>/atualizar', methods=['PUT'])
def atualizar_clientes(cliente_id):
    data =request.json
    
    cliente_editado = Cliente.get(Cliente.id == cliente_id)
    cliente_editado.nome = data['nome']
    cliente_editado.idade = data['idade']
    cliente_editado.email = data['email']
    cliente_editado.cidade = data['cidade']
    cliente_editado.save()

    #obter dados do clliente para editar
    

    return render_template('item.html', cliente=cliente_editado)

#criar def de deletear cliente/delete= DELETE

@home_clientes.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_clientes(cliente_id):
    cliente = Cliente.get(Cliente.id == cliente_id)
    cliente.delete_instance()
    return render_template('item.html', cliente=cliente)

@home_clientes.route('/<int:cliente_id>')
def detalhes_cliente(cliente_id):
    cliente=Cliente.get(Cliente.id == cliente_id)
    return render_template('detalhes_cliente.html', cliente=cliente)

routes/home.py
from flask import Flask, Blueprint, render_template
home_route= Blueprint('home', __name__)
@home_route.route('/')

def home():
      from models.clientedb import Cliente
      return render_template('index.html', clientes=Cliente)

templates/detalhes_cliente.html
<ul> 
    <li>id: {{ cliente.id }}</li>
    <li>Nome: {{ cliente.nome }}</li>
    <li>Email: {{ cliente.email }}</li>
    <li>Idade:{{ cliente.idade }}</li>
    <li>Cidade:{{ cliente.cidade }}</li>
 
</ul>

templates/form_clientes.html
<form class=" c-form"
  {% if cliente%}
    action="{{url_for('clientes.atualizar_clientes', cliente_id=cliente.id)}}" 
  {%else%}
    action="{{url_for('clientes.adicionar_clientes')}}" 
  {%endif%}

  method="{% if cliente%}PUT{%else%}POST{%endif%}"
  
  {% if cliente%}
    
    c-swap="#cliente-{{cliente.id}}"
  {% else %}
    c-append="#listar-clientes"
  {% endif %} 
  
   c-reload-container="true">
  
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name = "nome" {%if cliente%} value="{{cliente.nome}}" {%endif%}>
    </div>

    <div class="mb-3">
      <label id="label-target" class="form-label">Email</label>
      <input type="text"  class="form-control" name ="email" {%if cliente%} value="{{cliente.email}}" {%endif%}>
    </div>

      <div class="mb-3">
        <label class="form-label">Idade</label>
        <input type="text" class="form-control" name = "idade" {%if cliente%} value="{{cliente.idade}}" {%endif%}>
      </div>
  
    <select class="form-select" aria-label="Default select example" name="cidade" {%if cliente%} value="{{cliente.cidade}}" {%endif%}>
        <option selected>Selecione sua cidade </option>
        <option value="Acre">Acre</option>
        <option value="Alagoas">Alagoas</option>
        <option value="Amapá">Amapá</option>
        <option value="Amazonas">Amazonas</option>
        <option value="Bahia">Bahia</option>
        <option value="Ceará" >Ceará</option>
        <option value="Espírito Santo">Espírito Santo</option>
        <option value="Goiás">Goiás</option>
        <option value="Maranhào">Maranhão</option>
        <option value="Mato Grosso">Mato Grosso</option>
        <option value="Mato Grosso do Sul">Mato Grosso do Sul</option>
        <option value="Minas Gerais">Minas Gerais</option>
        <option value="Pará">Pará</option>
        <option value="Paraíba">Paraíba</option>
        <option value="Paraná">Paraná</option>
        <option value="Pernambuco">Pernambuco</option>
        <option value="Piauí">Piauí</option>
        <option value="Rio de Janeiro">Rio de Janeiro</option>
        <option value="Rio Grande do Norte">Rio Grande do Norte</option>
        <option value="Rio Grade do Sul">Rio Grande do Sul</option>
        <option value="Rondônia">Rondônia</option>
        <option value="Roraima">Roraima</option>
        <option value="Santa Catarina">Santa Catarina</option>
        <option value="São Paulo">São Paulo</option>
        <option value="Sergipe">Sergipe</option>
        <option value="Tocantis">Tocantins</option>
      </select>
    </div>
<h1><button type="submit" class="btn btn-primary">{%if cliente%} Salvar {%else%} Adicionar {%endif%} </button>
  </h1>

  </form>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cadastro Clientes</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/app.css')}}">
  </head>
  <body>
    <h1 class="text-center">Clientes</h1>

    <!--formulario adicionar clientes-->
    <div id="form-clientes"c-container="{{ url_for('clientes.form_clientes') }}"></div>
    <hr>

    <!--formulario listar clientes-->
    <div c-container="{{ url_for('clientes.listar_clientes') }}"></div>

    <div class="modal" id ="exampleModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Informações do usuario</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="exibir-cliente">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js') }}"></script>
  </body>
</html>  

templates/item.html
<tr class id="cliente-{{cliente.id}}">
    <th scope="row">{{cliente.id}}</th>
    <td>{{cliente.nome}}</td>
    <td>{{cliente.email}}</td>
    <td>{{cliente.idade}}</td>
    <td>{{cliente.cidade}}</td>
  
     <td> <button class="btn btn-primary" type="button" c-get="{{url_for('clientes.editar_clientes', cliente_id=cliente.id)}}"
      c-target="#form-clientes"
      >Editar
   </button> 
   </td>

     <td> <button class="btn btn-danger"  c-delete="{{url_for('clientes.delete_clientes', cliente_id=cliente.id)}}" type="button" 
        c-remove-closest="tr"> Deletar

     </button>
      </td>

       <td> <button class="btn btn-secondary" type="button" c-get="{{url_for('clientes.detalhes_cliente', cliente_id=cliente.id)}}"
      c-target="#exibir-cliente"
      data-bs-toggle="modal" data-bs-target="#exampleModal">
      Mostrar</button>
        
  
    </td>
      </tr>

templates/listar_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Idade</th>
        <th scope="col">Cidade</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="listar-clientes"> 

      {%for cliente in clientes %}
        {%include 'item.html'%}
      {% endfor %}
    </tbody>
  </table> 